version: 2.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_commits:
  message: /^docs|^chore|^ci\(github\)|^ci\(travis\)/
environment:
  nodejs_version: "12"
image: Visual Studio 2017
shallow_clone: true
install:
- ps: Install-Product node $env:nodejs_version
- cmd: >-
    node -v

    npm -v

    vcpkg version

    npm install -g lcpkg

    lcpkg config vcpkg.root C:\Tools\vcpkg

    lcpkg install

    lcpkg install --arch x64

    lcpkg install --platform uwp

    lcpkg install --platform uwp --arch x64
before_build:
- cmd: copy .\include\LCUI\config.win32.h.in .\include\LCUI\config.h
build_script:
  - msbuild build/windows/LCUI.sln /p:Configuration=Debug /p:Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild build/windows/LCUI.sln /p:Configuration=Debug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild build/windows/LCUI.sln /p:Configuration=Release /p:Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild build/windows/LCUI.sln /p:Configuration=Release /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
- cmd: lcpkg pack
artifacts:
  - path: 'lcpkg\dist\LCUI-*.lcpkg.zip'
cache:
  - c:\tools\vcpkg\installed
  - c:\tools\vcpkg\packages
