dist: bionic
language: c
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install valgrind libpng-dev libjpeg-dev libxml2-dev libfreetype6-dev libx11-dev lcov -qq
  - pip install --user cpp-coveralls
  - npm install
  - npm install --save-dev @commitlint/travis-cli

before_script:
  - ./node_modules/.bin/commitlint-travis && ./autogen.sh

script:
  - ./configure --enable-code-coverage
  - make
  - make distcheck
  - cd test
  - make
  - ./test
  - ../libtool --mode=execute valgrind --leak-check=full --error-exitcode=42 ./test

after_success:
  - coveralls --gcov-options '\-lp'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5b09ab7b7688f3152de0
      - https://hook.bearychat.com/=bwASg/travis/5b13360858a94c2c3caa6a4ab2dca9e5
    on_success: change
    on_failure: always
    on_start: never
