dist: trusty
language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install valgrind libpng-dev libjpeg-dev libxml2-dev libfreetype6-dev libx11-dev -qq

before_script: ./autogen.sh

script:
  - ./configure
  - make
  - cd test
  - make
  - ./test
  - valgrind --leak-check=full --error-exitcode=42 .libs/lt-test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5b09ab7b7688f3152de0
    on_success: change
    on_failure: always
    on_start: never
