language: c
sudo: required
services:
  - docker
jobs:
  include:
    - os: linux
      dist: bionic
      compiler: clang
      env: BADGE=linux
    - os: linux
      dist: bionic
      env:
        - WASM=1
        - BADGE=wasm
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      arch: arm64
      compiler: gcc
      env:
        - BADGE=arm64
        - NO_VALGRIND=1
    - os: osx
      env: BADGE=osx
  allow_failures:
    - os: osx

before_install:
  - sh ./scripts/ci-before-install.sh

before_script:
  - sh ./scripts/ci-before-script.sh

script:
  - sh ./scripts/ci-script.sh
