dist: bionic
language: c
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install valgrind libpng-dev libjpeg-dev libxml2-dev libfreetype6-dev libx11-dev lcov -qq
  - pip install --user cpp-coveralls
  - npm install
  - npm install --save-dev @commitlint/travis-cli

before_script:
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
  - ./node_modules/.bin/commitlint-travis && ./autogen.sh

script:
  - ./configure --enable-code-coverage
  - make
  - make distcheck
  - cd test
  - make
  - ./test
  - ../libtool --mode=execute valgrind --leak-check=full --error-exitcode=42 ./test

after_success:
  - if [[ $CC == clang ]] ; then coveralls --gcov-options '\-lp' --gcov 'llvm-cov gcov'  --exclude include --exclude test; fi
  - if [[ $CC == gcc ]] ; then coveralls --gcov-options '\-lp'  --exclude include --exclude test; fi
