language: c

compiler:
  - clang
  - gcc

before_script: ./autogen.sh

script:
  - ./configure
  - make
  - cd test
  - make
  - ./test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5b09ab7b7688f3152de0
    on_success: change
    on_failure: always
    on_start: never
