dist: trusty
language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install valgrind libpng-dev libjpeg-dev libxml2-dev libfreetype6-dev libx11-dev lcov -qq
  - pip install --user cpp-coveralls

before_script: ./autogen.sh

script:
  - ./configure --enable-code-coverage
  - make
  - make check
  - cd test
  - make
  - ./test
  - valgrind --leak-check=full --error-exitcode=42 .libs/lt-test

after_success:
  - coveralls --gcov-options '\-lp'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5b09ab7b7688f3152de0
      - https://hook.bearychat.com/=bwASg/travis/5b13360858a94c2c3caa6a4ab2dca9e5
    on_success: change
    on_failure: always
    on_start: never
